apps/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import ListView, DetailView, DeleteView, UpdateView, CreatView


urlpatterns = [
    url(r'^$', ListView.as_view(), name='home_view'),
    url(r'^client/edit/(?P<pk>\d+)/$', UpdateView.as_view(), name='edit_view'),
    url(r'^client/detail/(?P<pk>\d+)/$', DetailView.as_view(), name='detail_view'),
    url(r'^client/delete/(?P<pk>\d+)/$', DeleteView.as_view(), name='delete_view'),
    url(r'^client/create/$', CreatView.as_view(), name='create_view'),
    ]

client/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'', include('apps.core.urls', namespace='core')),
    url(r'^admin/', admin.site.urls),
    ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/core/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from .list_choices import UF



class ModelTime(models.Model):
    created = models.DateTimeField(_('criado em'), auto_now_add=True, auto_now=False)
    modified = models.DateTimeField(_('modificado em'), auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True


class Client(ModelTime):
    first_name = models.CharField(_('nome'), max_length=100)
    last_name = models.CharField(_('sobre nome'), max_length=100)
    phone = models.CharField(_('telefone'), max_length=11)
    cell = models.CharField(_('celular'), max_length=12, blank=True)
    address = models.CharField(_(u'endereço'), max_length=200)
    city = models.CharField(_('cidade'), max_length=150)
    zip_code = models.CharField(_(u'codigo postal'), max_length=8)
    state = models.CharField(_('estado'), max_length=80, choices=UF)
    cpf = models.CharField(_('cpf'), max_length=11)

    class Meta:
        ordering = ['first_name', 'last_name']
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    full_name = property(__str__)

    def get_absolute_url(self):
        return reverse("core:home_view")

apps/core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _
from .models import Client


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('__all__')

apps/core/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from .models import Client
from .forms import ClientForm




class ClientMixin(object):
    model = Client


class CreatView(ClientMixin, CreateView):
    form_class = ClientForm
    template_name = 'core/create_client.html'


class ListView(ClientMixin, ListView):
    template_name = 'core/index.html'
    context_object_name = 'clients'
    paginate_by = 4


class UpdateView(ClientMixin, UpdateView):
    template_name = 'core/client_update.html'
    is_update_view = True
    form_class = ClientForm


class DeleteView(ClientMixin, DeleteView):
    success_url = reverse_lazy('core:home_view')
  

class DetailView(ClientMixin, DetailView):
    template_name = 'core/client_detail.html'

apps/core/templates/base.html
<!DOCTYPE html>
{% load static %}

<html> 
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block description %}{% endblock %}">
    {% block title %}
    <title></title>
    {% endblock title %}
    <link rel="stylesheet" href="{% static "css/main.css" %}">
</head>
<body>
 
    <!-- include header -->
    {% include 'includes/header.html'%}

    {% block content %}{% endblock content %}

    <!-- include paginate -->
    {% include 'includes/paginate.html'%}

    <!-- include footer -->
    {% include 'includes/footer.html'%}

    <!-- js -->
    <script src="{% static "js/main.js" %}"></script>

</body>
</html>

apps/core/templates/core/client_confirm_delete.html
{% block title %}
    <title>client-crud | delete </title>
{% endblock title %}

<style type="text/css">
    .main{
        bottom: 50%;
        position: fixed;
        font-size: 20px;
        text-align: center;
        width: 100%;
    }
    .button{
        background: #0870E3;
        padding: 8px 10px 8px 20px;
        border: none;
        color: #fff;
        font-size: 15px;
        box-shadow: 3px 3px 2px #ccc;
        border-radius: 10px;
        text-decoration: none
    } 
    input{
        background: #0870E3;
        padding: 8px 10px 8px 20px;
        border: none;
        color: #fff;
        font-size: 15px;
        box-shadow: 3px 3px 2px #ccc;
        border-radius: 10px;
        cursor: hand;
        text-decoration: none;
    }
</style>

{% block content %}
<div class="container">
    <div class="main">
        <form method="post">
            {% csrf_token %}
                tem certeza que deseja deletar o cliente: <strong>{{ object }}</strong> ?
            <input type="submit" value="Sim" />
            <a class='button' href="{% url 'core:home_view' %}"> Não</a>
        </form>
    </div>
</div>
{% endblock content %}

apps/core/templates/core/client_detail.html
{% extends 'base.html' %}
{% load easy_mask %}
{% block title %}
        <title>client detail</title>
{% endblock title %}


{% block content %}
<div class="container">
    <div class="rows">
        <div class="detail-text">
            <h1>Detalhes do cliente</h1>  
        </div>
    </div>
</div>
<div class="container">
    <div class="rows">
        <div class="details">
            <div class="well">
                <div class="well-main">
                    <h2>{{ object.full_name }}</h2>
                    <p><strong>CPF: </strong> {{ object.cpf | cpf }}</p>
                    <p><strong>Tel. Fixo: </strong> {{ object.phone | phone }}</p>
                    <p><strong>Tel. Celular: </strong> {{ object.cell | phone }}</p>
                    <p><strong>Endereço: </strong> {{ object.address }}</p>
                    <p><strong>Cidade: </strong> {{ object.city }}</p>
                    <p><strong>Estado: </strong> {{ object.state }}</p>
                </div>
            </div>
            <div class="btn-detail">
                <a class="btns btn-styl btn-font" href="{% url 'core:edit_view' client.id %}"><span class="icons primary-button"></span> Editar</a>
                <a class="btns btn-styl btn-font" href="{% url 'core:home_view' %}"><span class="icons primary-button"></span> Voltar</a>
            </div>
        </div>
    </div>
    
</div>
{% endblock content %}

apps/core/templates/core/client_update.html
{% extends 'base.html' %}
{% load custom_class %}


{% block title %}
        <title>client update</title>
{% endblock title %}


{% block content %}
{{ form.non_field_errors }}
<div class="container">
    <div class="cont-area">
        <div class="form-area">
            <form method="post">
                {% csrf_token %}
                {{ form.first_name|class:'form-controls' }}
                {{ form.last_name|class:'form-controls' }}
                {{ form.cpf|class:'form-controls' }}
                {{ form.phone|class:'form-controls' }}
                {{ form.cell|class:'form-controls' }}
                {{ form.address|class:'form-controls' }}
                {{ form.city|class:'form-controls' }}
                {{ form.zip_code|class:'form-controls' }}
                {{ form.state|class:'form-controls' }}

                <input class="btns btn-styl btn-font edit-save" type="submit" value="Salvar" />
            </form>
        </div>
    </div>
</div>
{% endblock content %}

apps/core/templates/core/create_client.html
{% extends 'base.html' %}
{% load custom_class %}



{% block content %}
{{ form.non_field_errors }}
<div class="container">
    <div class="cont-area">
        <div class="form-area">
            <form method="post">
                {% csrf_token %}
                <p>Nome</p>
                {{ form.first_name|class:'form-controls' }}
                <p>Sobrenome</p>
                {{ form.last_name|class:'form-controls' }}
                <p>CPF</p>
                {{ form.cpf|class:'form-controls' }}
                <p>Telefone</p>
                {{ form.phone|class:'form-controls' }}
                <p>Celular</p>
                {{ form.cell|class:'form-controls' }}
                <p>Endereço</p>
                {{ form.address|class:'form-controls' }}
                <p>Cidade</p>
                {{ form.city|class:'form-controls' }}
                <p>CEP</p>
                {{ form.zip_code|class:'form-controls' }}
                <p>Estado</p>
                {{ form.state|class:'form-controls' }}

                <input class="btns btn-styl btn-font edit-save" type="submit" value="Salvar" />
            </form>
        </div>
    </div>
</div>
{% endblock content %}

apps/core/templates/core/index.html
{% extends 'base.html' %}
{% load easy_mask %}

{% block title %}
    <title>client-crud | bem vindo</title>
{% endblock title %}

    <div class="container">
        <div class="list-text">
            <h1>Lista de Clientes</h1>
        </div>
    </div>

{% block content %}

<div class="container">
    <div class="tab">
        <div class="new-client">
            <a class="btns btn-styl btn-font" href="{% url 'core:create_view' %}"><span class="icons primary-button"></span>Novo Cliente</a>
        </div>
        <table class="table-styl">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>CPF</th>
                    <th>Tel. Fixo</th>
                    <th>Tel. Celular</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            {% for client in clients %}
                <tr>
                    <td>{{ client.full_name | title }}</td>
                    <td>{{ client.cpf | cpf }}</td>
                    <td>{{ client.phone | phone }}</td>
                    <td>{{ client.cell | phone }}</td>
                    <td><a class='btns btn-styl' href="{% url 'core:detail_view' pk=client.id %}"><span class="icons primary-button"></span> Detail</a> <a class='btns btn-styl' href="{% url 'core:edit_view' client.id %}"><span class="icons secundary-button"></span> Edit</a> <a href="{% url 'core:delete_view' client.id %}" class="btns alt-btn-styl"><span class="icons alt-button"></span> Del</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>  
    </div>
</div>
{% endblock content %}

apps/core/templates/includes/footer.html
<footer class="footer">
    <div class="container">
        <div>
            <p>client-crud &copy; 2016 &middot; all righs reserved <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/" target="_blank"></a></p>
        </div>
    </div>
</footer>

apps/core/templates/includes/header.html
{% block header %}

<header class="header-main">
    
    <!-- include nav -->
    {% include 'includes/nav.html'%}

    
</header>
{% endblock header %}

apps/core/templates/includes/nav.html
<nav>
    <div class="container">
        <ul class="nav navbar">
            <li role="presentation" class="active"><a href="{% url 'core:home_view' %}">Home</a></li>
        </ul>
    </div>
</nav>

apps/core/templates/includes/paginate.html
<!-- pagination -->
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% endif %}
                {% for pg in page_obj.paginator.page_range %}
                    {% if page_obj.number == pg %}
                        <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
                    {% else %}
                        <li><a href="?page={{ pg }}">{{ pg }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% endif %}
            </ul>
        </div>
    </div>